{% set name = "streamlit-vis-timeline" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-vis-timeline-{{ version }}.tar.gz
  sha256: 76d788eaf31512560e5a521944009f3bdd996eca4f2e941019f260e81be92f12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - streamlit >=0.63

test:
  imports:
    - streamlit_timeline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/streamlit-timeline
  summary: Streamlit component for rendering vis.js timeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
